name: client_common
description: A sample command-line application.
publish_to: none
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.1 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  flutter: { sdk: flutter }
  http: ^0.13.4
  universal_html: ^2.0.8
  provider: ^6.0.1
  phoenix_wings: ^1.0.2
  logging: ^1.0.2
  flutter_markdown: ^0.6.10+2
  go_router: ^6.0.1
  shared_preferences: ^2.0.17
  lenra_components:
    git:
      url: git@github.com:lenra-io/lenra_components.git
      ref: v1.0.0-beta.51

flutter:
  uses-material-design: true
  assets:
    - assets/images/
