name: Release
on:
  push:
    branches:
      - main
      - beta
      - "*.x"

env:
  flutter_version: "3.0.x"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: |
            ${{ secrets.LENRA_UI_RUNNER_SSH }}
            ${{ secrets.LENRA_COMPONENTS_SSH }}
      - name: Install Flutter & Dependencies
        uses: subosito/flutter-action@v1.5.3
        with:
          flutter-version: ${{ env.flutter_version }}
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Setup node deps
        run: npm i conventional-changelog-conventionalcommits@4 @semantic-release/exec @semantic-release/git -D
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
        run: npx semantic-release@18
