name: Release

on:
  push:
    branches:
      - main
      - rc
      - beta
      - alpha
      - "*.x"

env:
  flutter_version: "3.10.x"

jobs:
  release:
    uses: lenra-io/github-actions/.github/workflows/release.yml@main
